#    __  __                   ___ _  __
#   |  \/  |___ _ _  __ _ ___/ __| |/ /
#   | |\/| / _ \ ' \/ _` / _ \__ \ ' <
#   |_|  |_\___/_||_\__, \___/___/_|\_\
#                   |___/
#  The MongoDB database management addon.
#
# Source code: https://github.com/Romitou/MongoSK
# Issue tracker: https://github.com/Romitou/MongoSK/issues
# Community help: https://github.com/Romitou/MongoSK/discussions

# The prefix and the field used by MongoSK in the storage of your documents.
# This field must be unique and not conflict with existing entries in your documents.
document-field: "__MongoSK__"

# You are currently experiencing problems, you want to know more about the real-time operations of MongoSK?
# You can activate this option to display real messages useful for debugging.
debug: false
