#  __  __                         _____ _  __
# |  \/  |                       / ____| |/ /
# | \  / | ___  _ __   __ _  ___| (___ | ' /
# | |\/| |/ _ \| '_ \ / _` |/ _ \\___ \|  <
# | |  | | (_) | | | | (_| | (_) |___) | . \
# |_|  |_|\___/|_| |_|\__, |\___/_____/|_|\_\
#                      __/ |
#                     |___/
#    The MongoDB database management addon.
#
# Source code: https://github.com/Romitou/MongoSK
# Issue tracker: https://github.com/Romitou/MongoSK/issues

# Enable this if you want to see more debug messages.
debug: false

# Beware! These options are disabled by default security.
# Enabling them will allow you and anyone with access to this machine
# to permanently delete without going back to certain data.
# Please activate them only if you know what you are doing.
allow-drop:
  collections: false
  databases: false
